### ISSUE TITLE
Same-Account snapshot copies

### ISSUE THREAD

**Issue by davidloutsch** [awslabs/aurora-snapshot-tool#1]
It doesn't look like same-account snapshot copying is available. Am I missing something? Is there a way to do this? Thanks!

**Comment by mrcoronel** [comment]
It's not possible at the moment, but it's not too difficult to add as a feature. I'll probably get that done in the next couple of weeks

**Comment by mrcoronel** [comment]
I'm merging it to MASTER. Closing issue
