### ISSUE TITLE
How to check destination settings?

### ISSUE THREAD

**Issue by XiaobingBenYu** [awslabs/aurora-snapshot-tool#10]
Hello,

I have setup one stack in us-west-1 region for source snapshot, and setup one stack in us-west-2 region for destination snapshot, I found two snapshots were created correctly in us-west-1 region, but I did not find any snapshots that were copied to us-west-2 region.

**Here are destination settings:**
Key | Value | Resolved Value
CodeBucket | DEFAULT_BUCKET |  
CrossAccountCopy | FALSE |  
DeleteOldSnapshots | TRUE |  
DestinationRegion | us-west-2 |  
KmsKeyDestination | None |  
KmsKeySource | None |  
LogLevel | ERROR |  
RetentionDays | 7 |  
SnapshotPattern | snapshot-db-dr |  
SNSTopic |   |  
SourceRegionOverride | NO

**Here are source settings:**
Key | Value | Resolved Value
BackupInterval | 2 |  
BackupSchedule | 0 19,21,23 * * ? * |  
ClusterNamePattern | snapshot-db-dr |  
CodeBucket | DEFAULT_BUCKET |  
DeleteOldSnapshots | TRUE |  
DestinationAccount | 000000000000 |  
LogLevel | ERROR |  
RetentionDays | 7 |  
ShareSnapshots | FALSE |  
SNSTopic |   |  
SourceRegionOverride | NO

Thanks,
Ben

**Comment by mrcoronel** [comment]
Hi @XiaobingBenYu , I believe you will need to set SourceRegionOverride to us-west-1 in for the stack you created in us-west-2
Please let me know if that fixed it for you

**Comment by mrcoronel** [comment]
Closing this one out. Please let us know if you are still having issues
