### ISSUE TITLE
Occasional rate limiting errors

### ISSUE THREAD

**Issue by flosell** [awslabs/aurora-snapshot-tool#11]
We are running this tool with quite a lot of snapshots being generated (once an hour, kept for 7 days for multiple clusters). 

In this configuration, we are seeing the occasional errors due to rate limiting: 

```
[ERROR]	2018-10-08T02:30:33.680Z	6153e97f-733f-4764-899c-a89c052312c8	Exception sharing dev-aurora-cluster20181001042229986400000001-2018-10-04-23-00: An error occurred (Throttling) when calling the ModifyDBClusterSnapshotAttribute operation (reached max retries: 4): Rate exceeded
```
or 
```
An error occurred (Throttling) when calling the ListTagsForResource operation (reached max retries: 4): Rate exceeded: ClientError
Traceback (most recent call last):
File "/var/task/lambda_function.py", line 49, in lambda_handler
ResourceName=snapshot_arn)
File "/var/runtime/botocore/client.py", line 314, in _api_call
return self._make_api_call(operation_name, kwargs)
File "/var/runtime/botocore/client.py", line 612, in _make_api_call
raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (Throttling) when calling the ListTagsForResource operation (reached max retries: 4): Rate exceeded
```

This happens often enough that it not only fails the Lambda but also the Step Function after retries. 

Is there a way to reduce the number of calls the tool makes or are we simply going beyond the limit of what's possible with the current implementation?

**Comment by mrcoronel** [comment]
Hi @flosell, how many instances of the tool are you running on the same account?

**Comment by flosell** [comment]
@mrcoronel one instance per account

**Comment by mrcoronel** [comment]
Is there any chance you'd have other tools/scripts hitting the RDS APIs? How many snapshots have you got in that account? 
There are a few optimisations that I could make (not too many though), but I won't have much time to implement them until next month. 
If you've got a support subscription, perhaps you could open a case so they can help you find out why your calls are being throttled?

**Comment by flosell** [comment]
I don't see anything else hitting the RDS APIs. We were running hourly snapshots for two clusters and seven day retention so about 340 snapshots. After reducing retention to three days we seem to be fine now so I'm guessing it's related to the number of snapshots. 
Also seems to affect only the lambda in the source account, not the destination account. 

I asked AWS support for some more information on their rate limiting, I'll update once I receive a response.

**Comment by lefthand** [comment]
I've seen the same errors. We have 200 snapshots. I opened a PR (#12) that should help with this. Seems to work so far in my tests.  The function is fetching tags for automated snapshots that will never be returned and manual snapshots are being fetched twice.

**Comment by lefthand** [comment]
Running over the weekend I didn't get any tag throttling. I did get throttled calling DescribeDBClusterSnapshots which is kind of confusing. It only happened once and was fine when it retired so I'm not worried.

**Comment by mrcoronel** [comment]
just merged the PR... the new version is in the buckets too... thanks for the contribution!
