### ISSUE TITLE
Support for Aurora PostgreSQL?

### ISSUE THREAD

**Issue by stephenchu** [awslabs/aurora-snapshot-tool#13]
The README.md says it's Aurora MySQL only. But then there is also #3 which is closed and says it appears PostgreSQL is also functional.

Can you tell me whether it is the case that this tools does support Aurora PostgreSQL? If so, then the README.md probably needs updating.

Thanks!

**Comment by ahartma1** [comment]
Yes the Readme was out of date last I checked, and you just need to change the engine in a couple places from aurora to aurora-postgresql

**Comment by mrcoronel** [comment]
@stephenchu Aurora PostgreSQL is fully functional. You don't need to change anything in the code. I've just updated the README file
