### ISSUE TITLE
Incomplete pagination prevents sharing

### ISSUE THREAD

**Issue by rts-rob** [awslabs/aurora-snapshot-tool#14]
# Problem

When an account has more than 25 Aurora cluster snapshots of any type, snapshots are no longer copied over to the target account.

# Root Cause

[snapshots_tool_utils.py](lambda/snapshots_tool_utils.py) uses custom pagination code. Somehow this pagination is limited to 25 rows. Once an account has more than 25 manual backups, snapshots are created but not shared, and thus are not copied over.

# Proposed Solution

Modify snapshots_tool_utils.py to use the built-in Boto paginator. A PR will be submitted against this issue.

**Comment by mrcoronel** [comment]
Sorry it took this long to review. I'm afraid I'm getting error messages when using the boto3 paginator. Lambda uses an old version of boto3, which does not include paginator for some of the API calls (including describe_db_clusters). That's the reason I wrote custom code. I haven't encountered the issue and I have more than 25 snapshots in my account you mentioned.

**Comment by mrcoronel** [comment]
I updated the runtime environment to python 3.7 and it's working now. I'll merge to master in the next few days. Thanks!
