### ISSUE TITLE
An error occurred (KMSKeyNotAccessibleFault) when calling the CopyDBClusterSnapshot operation: Specified KMS key [None] does not exist, is not enabled or you do not have permissions to access it.

### ISSUE THREAD

**Issue by fliphess** [awslabs/aurora-snapshot-tool#25]
My snapshots are not encrypted, but for some reason I still get this KMS error when copying cross-account and cross-region. 

Are there any policies or configurations that I need to create outside of cloudformation?

**Comment by mrcoronel** [comment]
Hi @fliphess, copying non-encrypted snapshots should work. Encryption has become the new default for new RDS instances. Is it possible that you are using encryption using the default AWS Managed KMS key? If not, please provide some more information, such as logs

**Comment by fliphess** [comment]
@mrcoronel, Sorry to waste your time, you are right, the encryption is on by default, causing this error. I reapplied the CF template using the correct key id's and it looks a lot better now. 

Closing this issue as it's not in the software :)

**Comment by teseo24** [comment]
Hi @fliphess, @mrcoronel 

I have the same problem, I put in the input the id of the default kms but I get the same error
Can you share your screentshots of cloudformation parameters

Thanks in advance

**Comment by fliphess** [comment]
@teseo24 This tool only works if your RDS cluster is encrypted with a self-managed kms key, instead of the default `aws/kms` aws-managed kms key. The aws managed ones cannot be shared cross-account resulting in the error I experienced.

**Comment by teseo24** [comment]
Hi 

I have Two accounts. The first one has 10 instances, all with default rds key in us-east-1. That I want is to take snapshotS for all instances and share with the second account in us-East-2

The first json works whatever kms key has the instance but the second json doesnt work

So I did the next. In account one, I have created a kms key and the restore the last snapshot with this new Kms

I upload the second json in the account of destination but it doesnt work. What I am missing

Thanks in advance

Martin

**Comment by fliphess** [comment]
Hey @teseo24! 

For what I understand (please someone, correct me if i'm wrong): the decryption and re-encryption with the kms key of the receiving account is done on the receiving account side, not on the source account side. 

This implies that the kms key used for encrypting on the source side, should be accessible on the receiving side for decryption so it can be encrypted using a kms key in the destination account. 

The default `aws/kms` cannot be shared with the other account, as this is an AWS managed key that you cannot use cross-account. 

What I did: I recreated my database clusters using my own KMS managed keys.
When that is done you can remove this util from CF and reinstall it again and it should work.

**Comment by teseo24** [comment]
Hi 

Thanks for your quickly answer. 

What I did is: I  recreated my database clusters using my own KMS managed keys in the source account

So What I am missing is to export this key or is sharing this key to destination key, is it right? Other question in the destination account,  in what region can upload the json of destination? in the same as source or in the region I want to share (The source json is in us-east-1 and the destination will to be in us-east-2)

I would like to copy snapshots from account A in Virginia (one is with my own KSM key) to account B in Ohio. 

Thanks in advance

Martin

**Comment by fliphess** [comment]
@teseo24 You indeed need to create some policies for your KMS key so it's shared between the source and dest account.  (as mentioned in the readme in `Installing in the source account`: https://aws.amazon.com/premiumsupport/knowledge-center/share-cmk-account/)

**Comment by vikashkodati** [comment]
Hello, I am facing a similar issue,  my primary region cluster is us-west-2 and I am trying to create a secondary replica in us-east-1. I provided a refer to the west kms_key_id in the east module definition. I end up with this error: 

`Error: error creating RDS cluster: KMSKeyNotAccessibleFault: The specified KMS key [arn:aws:kms:us-west-2:515379432062:key/5cd91929-2c56-46a2-a4d8-47b3ef44ad75] does not exist, is not enabled or you do not have permissions to access it.
	status code: 400, request id: a44be0d7-a555-495d-af48-0381c72f8939`

**Comment by fliphess** [comment]
@vikashkodati 

The error is very generic, but it means that the key is not accessible from the lambda's in the other account and or region.

What helped for me was trying to access the KMS key from the other account and other region outside the snapshot tool: If it works using the AWS cli tool, you can safely assume it works using this tool as well:

```
aws kms describe-key --key-id arn:aws:kms:${region}:${account_id}:key/${key_id}
```

Also, (sorry, I don't remember exactly which one of the two it was), but it took me some time to find out not to use the key id but instead the full arn to the key (or the other way around: Use the key id, not the full arn). 
You'll find out soon enough which value you should use if you are sure the key is accessible in the other region. The error is exactly the same in both cases, so try to install both ways and see which one works if in doubt.
