### ISSUE TITLE
Unable to copy AWS managed KMS encrypted snapshots between accounts

### ISSUE THREAD

**Issue by tabascoterrier** [awslabs/aurora-snapshot-tool#26]
I have an Aurora cluster, encrypted with the AWS managed KMS key.  The snapshot tool successfully creates a snapshot in the source account, and shares it with the backup account, however the copy into the backup account fails with:

> The source snapshot KMS key [arn:aws:kms:(source account arn)] does not exist, is not enabled or you do not have permissions to access it.

Being an AWS managed key, I'm (as far as I can tell) unable to grant the backup account permissions to use it.

I'd much rather not recreate the cluster with a CMK.  Is there a a way of working around this?

**Comment by mrcoronel** [comment]
Hi @tabascoterrier, I'm afraid that's a documented limitation of using AWS managed KMS keys. You can't copy those snapshots across accounts.

**Comment by tabascoterrier** [comment]
Ah well, thanks for confirming @mrcoronel , I feared that was the case!

**Comment by mherrmann** [comment]
AWS documentation on the associated limitation: https://aws.amazon.com/premiumsupport/knowledge-center/share-encrypted-rds-snapshot-kms-key/
