### ISSUE TITLE
Snapshot issue

### ISSUE THREAD

**Issue by terakota** [awslabs/aurora-snapshot-tool#32]
Every time step funcion runs for snapshot making on one instance it trows "errorMessage": "Could not back up every cluster. Backups pending: 1" if I run it on multiple instances  "errorMessage": "Could not back up every cluster. Backups pending: 3" any idea hot to solve it?

**Comment by mrcoronel** [comment]
Hi @terakota, there may be more information in the logs about why they are failing. Have you had a look at the Cloudwatch logs for the takeSnapshot Lambda function?

**Comment by terakota** [comment]
Hey @mrcoronel, thanks for pointing to those logs. It seems some permissions is missing.
An error occurred (AccessDenied) when calling the CreateDBClusterSnapshot operation: User: arn:aws:sts::...:assumed-role/snapshots-tool-aurora-sourc-iamroleSnapshotsAurora-.../snapshots-tool-aurora-sou-lambdaTakeSnapshotsAuror-... is not authorized to perform: rds:AddTagsToResource on resource: arn:aws:rds:us-east-1:...:cluster-snapshot:...

**Comment by terakota** [comment]
adding additional permissions
 "Action": [
                "rds:AddTagsToResource",
                "rds:RemoveTagsFromResource",
 on snapshots-tool-aurora-sourc-iamroleSnapshotsAurora-... role solved this issue.
