### ISSUE TITLE
Missing rds:addTagsToResources

### ISSUE THREAD

**Issue by keroloswilliam** [awslabs/aurora-snapshot-tool#34]
the problem: 

```
is not authorized to perform: rds:AddTagsToResource on resource: <ResourceArn>
```

Appeared on:
- dest-lambda Copy Snapshots Aurora
- source-lambda Backup Snapshots Aurora

I solved it now by adding the permission in the template under ` iamroleSnapshotsAurora`  and it worked fine afterwards

**Comment by fschroder-slyp** [comment]
Confirmed. Should be a simple fix. Is this project still active?
