### ISSUE TITLE
share encrypted snapshot not copying over to another region and account

### ISSUE THREAD

**Issue by ccleow** [awslabs/aurora-snapshot-tool#7]
The take snapshot and share snapshot work fine. however the snapshot can not be copied over to different region and account

**Comment by mrcoronel** [comment]
Hi @ccleow this is functionality that's been working for a very long time. Could you elaborate on what you are trying to do, from which regions, engines, encryption settings, etc? I can try to help you

**Comment by ccleow** [comment]
Hi mrcoronel,
I'm trying to do a cross account, cross region aurora db instance backup. My source aurora db instance is encrypted with a non default kms key and resides in eu-west-1 and my destination region is eu-central-1. The takesnapshot lambda and sharesnapshot lambda is working fine, as I had verified that a manual snapshot was created and share to another aws account i specified. What I have been waiting for is to have the share manual snapshot to be copied over to the destination aws account and region. Which had not happened in my case. I set the takesnapshot the run every hour, sharesnapshot to run every 10 minutes as default and copysnapshot to run every 30 minutes. Is there anything I have miss out?

**Comment by mrcoronel** [comment]
Hi @ccleow, have you deployed both CF templates in the region where you are running your clusters (both in the source and destination account). I find that's a common mistake
Also, have you created KMS keys both in the source and destination regions in the destination account? KMS is a regional service so you will need encryption keys in the destination account both in eu-west-1 and eu-central-1 as the copy is done in two steps and snapshots get re-encrypted with each one. 

Also, the times at which sharesnapshot and copysnapshot are not supposed to be configurable. Have you modified something in the setup?

**Comment by ccleow** [comment]
If my source is at account A, region: eu-west-1 and i would like to backup to account B region: eu-central-1.
I suppose my source CF need to be deployed in account A, region:eu-west-1 and the dest CF to account B, region:eu-central-1. Is that correct?

**Comment by ccleow** [comment]
Hi mrcoronel,
I found my answer on the README and i know what went wrong.
I will close this issue. Thanks!

IMPORTANT Run the Cloudformation templates on the same region where your Aurora clusters run (both in the source and destination accounts). If that is not possible because AWS Step Functions is not available, you will need to use the SourceRegionOverride parameter explained below.
